services:
  bottymcbotface:
    image: bottymcbotface-bot
    user: node
    working_dir:  /bottymcbotface/bot
    environment:
      - NODE_ENV=production
    volumes:
      - ../logs:/logs
      - ../data:/data
      - ./environment/dotenv-prod.txt:/bottymcbotface/bot/.env
      - ../temp:/temp
    command: "npm run prodstart"
    restart: always
